openapi: 3.0.0
info:
  title: Comprehensive Mock API
  version: 1.0.0
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      in: header
      name: X-API-Key
    apiKeyQuery:
      type: apiKey
      in: query
      name: api_key
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /auth/api-key-header:
    get:
      summary: API Key in Header
      security:
        - apiKeyHeader: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true

  /auth/api-key-query:
    get:
      summary: API Key in Query
      security:
        - apiKeyQuery: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true

  /auth/basic:
    get:
      summary: Basic Auth
      security:
        - basicAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true

  /auth/bearer:
    get:
      summary: Bearer Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authenticated:
                    type: boolean
                    example: true

  /headers:
    get:
      summary: Custom Headers
      responses:
        '200':
          description: OK
          headers:
            X-Custom-Header:
              schema:
                type: string
                example: "Mocked-Header-Value"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Check response headers"

  /realistic:
    get:
      summary: Realistic Data Generators
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  email:
                    type: string
                    format: email
                  website:
                    type: string
                    format: url
                  firstName:
                    type: string
                  lastName:
                    type: string
                  fullName:
                    type: string
                  phoneNumber:
                    type: string
                  address:
                    type: string
                  city:
                    type: string
                  zipCode:
                    type: string
                  country:
                    type: string
                  companyName:
                    type: string
                  jobTitle:
                    type: string
                  bio:
                    type: string
                  price:
                    type: number
                  amount:
                    type: number
                  createdAt:
                    type: string
                    format: date-time

  /images:
    get:
      summary: Image and Avatar Generators
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  profilePicture:
                    type: string
                    description: Realistic Avatar URL
                  productImage:
                    type: string
                    description: Realistic Image URL
                  thumbnail:
                    type: string
                    description: Realistic Image URL

  /shaping:
    post:
      summary: Request Body Shaping
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                role:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  role:
                    type: string
                  status:
                    type: string
                    example: "active"

  /validation:
    get:
      summary: Parameter Validation
      parameters:
        - name: required_param
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  received:
                    type: string
